import { PAYMENT_PURPOSES, type PaymentPurpose } from "@/domain/enums";
import { toPaystackAmount, type Kobo } from "@/lib/money";
import { initializeTransaction, verifyTransaction } from "@/server/paystack";
import { uuidv7 } from "@/lib/uuidv7";

/**
 * TAKING MONEY FOR THE CLUB — §9, §11 M8.
 *
 *   §9, Paystack: "Subscriptions, guest overage, account top-up. WEBHOOK-DRIVEN
 *    STATE, NEVER CLIENT-REPORTED SUCCESS. Idempotent on gateway_reference.
 *    Reconciliation job for webhooks that never arrive. Amounts in kobo
 *    throughout."
 *
 * The gateway plumbing — HMAC verification, the API calls, constant-time
 * comparison — is in src/server/paystack.ts and is shared with the first-visit
 * booking flow. This module is what the MANAGEMENT system needs on top: the
 * reference format, the metadata contract, and the rule that a transaction is
 * never started from a number the browser supplied.
 *
 * ===========================================================================
 * THE REFERENCE IS OURS AND IT IS A UUIDv7
 *
 * Paystack accepts a merchant reference and echoes it back on every webhook.
 * The unique index on `payments.gateway_reference` (§3.5) makes it the
 * idempotency key §12.1 asks for, so it has to be generated by us, once, before
 * the transaction is initialised.
 *
 * UUIDv7 rather than a readable string for the reason §7 gives everywhere else:
 * it is generated without a round trip, it sorts by creation time, and it
 * cannot collide with a retry that produced a second attempt for the same
 * charge. A human-readable reference — `SUB-2026-0142` — was rejected because
 * the first thing anyone does with a readable reference is derive it from data
 * rather than store it, and two attempts at one charge then share a reference
 * and the second is silently swallowed as a duplicate.
 *
 * ===========================================================================
 * THE METADATA CONTRACT
 *
 * The webhook is the first time the server hears from Paystack about a payment,
 * and it must be able to attribute it without trusting anything the payer
 * typed. Everything needed travels in metadata, set here, server-side:
 *
 *   personId   who the payment is for. §3.5's `payments.person_id`.
 *   purpose    one of §3.5's PAYMENT_PURPOSES.
 *   chargeId   the charge this settles, or absent for a top-up.
 *
 * `readIntent` below is the only reader, and it validates rather than casts —
 * webhook bodies are attacker-influenced even when the signature is valid,
 * because the signature proves Paystack sent it, not that the metadata is
 * anything we recognise.
 */

/* ============================================================================
   STARTING A PAYMENT
   ========================================================================= */

export type PaymentIntent = {
  readonly personId: string;
  readonly purpose: PaymentPurpose;
  readonly chargeId: string | null;
};

export type StartResult =
  | {
      readonly ok: true;
      readonly authorizationUrl: string;
      readonly gatewayReference: string;
    }
  | { readonly ok: false; readonly reason: string };

/**
 * Begin a Paystack transaction for a member.
 *
 * The amount is a `Kobo` from the caller's own arithmetic — a charge total, or
 * a top-up the member chose from a fixed set. It is never a number that arrived
 * in a request body: §9's whole first rule, and src/server/paystack.ts states
 * the same thing at greater length ("a client-supplied amount is a
 * client-controlled price").
 */
export async function startPayment(input: {
  readonly email: string;
  readonly amountKobo: Kobo;
  readonly intent: PaymentIntent;
  readonly callbackUrl: string;
}): Promise<StartResult> {
  const gatewayReference = uuidv7();

  const result = await initializeTransaction({
    email: input.email,
    amountKobo: toPaystackAmount(input.amountKobo),
    reference: gatewayReference,
    callbackUrl: input.callbackUrl,
    metadata: {
      /* Flat scalars. Paystack's metadata round-trips objects unevenly across
         API versions and the webhook is not the place to discover it. */
      armoryPersonId: input.intent.personId,
      armoryPurpose: input.intent.purpose,
      armoryChargeId: input.intent.chargeId ?? "",
    },
  });

  if (!result.ok) return { ok: false, reason: result.error };

  return {
    ok: true,
    authorizationUrl: result.authorizationUrl,
    /* Paystack echoes our reference; taking theirs rather than ours keeps the
       two identical even if it ever normalises the string. */
    gatewayReference: result.reference,
  };
}

/* ============================================================================
   READING A WEBHOOK
   ========================================================================= */

const UUID =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Pull the club's intent out of a webhook's metadata, or refuse it.
 *
 * Validated, never cast. A signed webhook proves Paystack sent it and nothing
 * about what is inside — the metadata could be from the first-visit booking
 * flow, which shares this Paystack account and sets entirely different keys.
 * Returning null for those is correct and is how the route tells "not ours"
 * from "ours and broken".
 */
export function readIntent(
  metadata: Record<string, unknown> | undefined,
): PaymentIntent | null {
  if (!metadata) return null;

  const personId = metadata.armoryPersonId;
  const purpose = metadata.armoryPurpose;
  const chargeId = metadata.armoryChargeId;

  if (typeof personId !== "string" || !UUID.test(personId)) return null;
  if (
    typeof purpose !== "string" ||
    !(PAYMENT_PURPOSES as readonly string[]).includes(purpose)
  ) {
    return null;
  }

  return {
    personId,
    purpose: purpose as PaymentPurpose,
    /* An empty string is "no charge" — see the metadata note above on why these
       are flat scalars rather than nulls. */
    chargeId:
      typeof chargeId === "string" && UUID.test(chargeId) ? chargeId : null,
  };
}

/**
 * Ask the gateway directly whether money moved.
 *
 * §9's reconciliation job needs this, and so does any path that suspects a
 * webhook was lost. It is the authoritative answer — the only one — which is
 * why `stalePendingPayments` in money.ts reports rather than decides.
 */
export async function confirmWithGateway(
  gatewayReference: string,
): Promise<
  | { readonly ok: true; readonly paid: boolean; readonly amountKobo: number }
  | { readonly ok: false; readonly reason: string }
> {
  const result = await verifyTransaction(gatewayReference);

  return result.ok
    ? { ok: true, paid: result.paid, amountKobo: result.amountKobo }
    : { ok: false, reason: result.error };
}
